version: '3.8'

services:
  app:
    container_name: starsoft-frontend-challenge
    image: henriquecostaa/starsoft-frontend-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production